CHUNK       = 2048
SAMPLE_RATE = 44100

LO_CUT  = CHUNK // 128
MED_CUT = CHUNK // 4
HI_CUT  = CHUNK // 2 + 1

SP_SCALE = 2.0 / (128.0 * CHUNK)

AVG_COUNT_RATE_DEFAULT = 20
AVG_COUNT_RATE_MIN     = 10
AVG_COUNT_RATE_MAX     = 50

DM_TIME_RATE       = 2400
DM_SEMITONE_OFFSET = 15

MIDI_SPACE_NOTE = 106

DEFAULT_LOW_THRESHOLDS  = (100, 300, 500)
DEFAULT_HIGH_THRESHOLDS = (100, 300, 500)

CUTOFF_SLIDER_MAX = 40_000

WINDOW_W = 1200
WINDOW_H = 800

__all__ = [
    'CHUNK', 'SAMPLE_RATE',
    'LO_CUT', 'MED_CUT', 'HI_CUT', 'SP_SCALE',
    'AVG_COUNT_RATE_DEFAULT', 'AVG_COUNT_RATE_MIN', 'AVG_COUNT_RATE_MAX',
    'DM_TIME_RATE', 'DM_SEMITONE_OFFSET',
    'MIDI_SPACE_NOTE',
    'DEFAULT_LOW_THRESHOLDS', 'DEFAULT_HIGH_THRESHOLDS',
    'CUTOFF_SLIDER_MAX',
    'WINDOW_W', 'WINDOW_H',
]
